### ISSUE TITLE
Add "crop" to the MoBIE spec

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie.github.io#44] opened 2021-05-10 13:09 UTC
As discussed in #32 and https://github.com/bigdataprocessor/bigdataprocessor2/issues/168, it would be good to express a "crop" in the MoBIE spec.
I think the best option would be to add this as an additional source transform and/or viewer transform.
Let me know what you think, @tischi @martinschorb @K-Meech.

**Comment by constantinpape** [comment] 2021-05-11 07:28
> That sounds very good. 

Ok, should we go with:
```
{"crop": {"start": [0.0, 0.0, 0.0], "stop": [10.1, 11.2, 12.3]}}
```
?
Any other preferences?

> And then I would suggest it is users responsibility to first add a source transform to, e.g. rotate, the source into a space where the crop can be expressed in Cartesian coordinates.

Exactly.

**Comment by constantinpape** [comment] 2021-05-11 14:21
Ok, I have added the crop transform to the spec now.
It is defined like this:
```
{
  "crop": {
    "min": [0.0, 0.0, 0.0],
    "max": [1.1, 2.2, 3.3],
    "sources": ["mySourceNames"],
    "timepoints": [0, 1, 2]
  }
}
```
The `timepoints` field is optional; if it is missing the transform will be applied to all timepoints.

**Comment by martinschorb** [comment] 2021-05-13 06:34
What would you think would be the best strategy to make the cropped sources available in MoBIE? Would you list them as extra 'images'? or 'bookmarks'?

I think it would also be beneficial to give each crop a 'name' or ID to be able to identify them (for example when used in a gallery).

**Comment by constantinpape** [comment] 2021-05-14 15:15
> What would you think would be the best strategy to make the cropped sources available in MoBIE? Would you list them as extra 'images'? or 'bookmarks'?
> 

This depends on what you want to achieve. If it makes sense to look at the cropped source independently, then it can be provided as an extra image. If not, it should only be added to the bookmarks.
But this is up to whoever creates the MoBIE project; it's possible to express both options in the current spec (once crop is implemented in the fiji viewer).

> I think it would also be beneficial to give each crop a 'name' or ID to be able to identify them (for example when used in a gallery).

I think that's the case anyway; each source in the view will be listed.  But let's see how this looks once we have the crop functionality in the viewer; I think it's much easier to discuss this when we have a working example already.

**Comment by martinschorb** [comment] 2021-05-14 15:37
> I think that's the case anyway; each source in the view will be listed.

One source can have multiple crop regions. Hence I see the need for an independent tag for those. Or would you suggest to define multiple sources from the same image but pointing to different crop regions?

**Comment by tischi** [comment] 2021-05-14 17:07
> Or would you suggest to define multiple sources from the same image but pointing to different crop regions?

Currently that's what one would need to do I think as the transformations do not change the name of the sources. Adding them as an extra sources with the cropped default view to the dataset.json also could allow you to give them a name of your liking. I thus think that could be a good mechanism.

However, I think the current spec requires that [name of the source in dataset.json](https://github.com/mobie/zebrafish-lm-datasets/blob/288e9f12426a45a8551827d86bc84084a0561849/data/membrane/dataset.json#L4) MUST be the same as the [name in the xml](https://github.com/mobie/zebrafish-lm-datasets/blob/288e9f12426a45a8551827d86bc84084a0561849/data/membrane/images/local/membrane-056F63395C_lynEGFP.xml#L15). We would need to allow for them to be different in order to add the same source several times with different crops, because the names of the sources in dataset.json MUST be unique.

**Comment by tischi** [comment] 2021-05-14 17:40
Frankly, above comment was just a knee-jerk reaction 😄 

Second thought is that this is not a good idea. 

The `sources` should just define the "raw" sources and any special "view" on them (such as a crop) should very likely be defined in the `views`.

**Comment by constantinpape** [comment] 2021-05-14 18:13
We could add an optional `name` to the source transforms. If there is no such name, the UI shows the source name. If the name is specified in the transform, this name is used. This introduces some corner cases, because multiple names could be specified for one source via multiple transforms. In that case, we could either throw a runtime error, or just use the last or first name.

**Comment by tischi** [comment] 2021-05-15 08:11
> We could add an optional name to the source transforms.

I think maybe that issues solves itself when we do [this](https://github.com/mobie/mobie.github.io/issues/46)? Because then the name is automatically determined by the view that applies the transformation(s).

**Comment by tischi** [comment] 2021-05-15 09:04
I think we may need another field in the `crop`, namely `shiftToOrigin` specifying whether after the crop the region should be moved to (`true`) `(0,0,0)` or whether it should (`false`) stay in physical space where it was. I think we need both. `true` in order to overlay onto other sources, `false` in order to generate a gallery using the `grid` (where currently the sources are shifted relative to their current position in space).

**Comment by constantinpape** [comment] 2021-05-15 09:15
> I think maybe that issues solves itself when we do [this](https://github.com/mobie/mobie.github.io/issues/46)? Because then the name is automatically determined by the view that applies the transformation(s).

While I agree that we should do the change you proposed in #46 I don't think it solves the particular issue here:
the issue is that we can have multiple transforms of the same source in a single (grid) view, for example the same source with different crops applied to it. Now we need different names to distinguish this. The only solution I see here is to add an optional `name` to `sourceTransforms`: https://github.com/mobie/mobie.github.io/issues/44#issuecomment-841416722.

> I think we may need another field in the `crop`, namely `shiftToOrigin` specifying whether after the crop the region should be moved to (`true`) `(0,0,0)` or whether it should (`false`) stay in physical space where it was. I think we need both. `true` in order to overlay onto other sources, `false` in order to generate a gallery using the `grid` (where currently the sources are shifted relative to their current position in space).

Makes sense and I can add it. Do you think this should be mandatory or optional? If optional, what would be the default? I think `true`?!

**Comment by tischi** [comment] 2021-05-16 11:40
> the issue is that we can have multiple transforms of the same source in a single (grid) view, for example the same source with different crops applied to it

Good point! Let's add an optional name to the transform. I guess the point would be to append this to the source name?

> Do you think this should be mandatory or optional?

Yes, let's do optional with default true. Is "shiftToOrigin" the best name for the field?

**Comment by constantinpape** [comment] 2021-05-16 13:12
> Good point! Let's add an optional name to the transform. I guess the point would be to append this to the source name?

:+1: 

> Yes, let's do optional with default true. Is "shiftToOrigin" the best name for the field?

Not sure; I can't think of anything better right now.

**Comment by tischi** [comment] 2021-05-16 14:37
I am now not so sure about whether we should _append_ the name.
The point is that one has to exactly match the name of the transformed (e.g. cropped) source when [referring to it in a grid view](https://github.com/mobie/zebrafish-lm-datasets/blob/288e9f12426a45a8551827d86bc84084a0561849/data/membrane/dataset.json#L1310).
Thus one would need to know how exactly MoBIE appends (e.g. space or dash separated).
Currently I feel it is easier to fully _replace_ the name (this also avoids the issue that names could get very long).

**Comment by tischi** [comment] 2021-05-16 14:38
Sorry, [here is the place](https://github.com/mobie/zebrafish-lm-datasets/blob/288e9f12426a45a8551827d86bc84084a0561849/data/membrane/dataset.json#L1375) that I meant.

**Comment by constantinpape** [comment] 2021-05-16 17:14
> I am now not so sure about whether we should _append_ the name.
> The point is that one has to exactly match the name of the transformed (e.g. cropped) source when [referring to it in a grid view](https://github.com/mobie/zebrafish-lm-datasets/blob/288e9f12426a45a8551827d86bc84084a0561849/data/membrane/dataset.json#L1310).
> Thus one would need to know how exactly MoBIE appends (e.g. space or dash separated).
> Currently I feel it is easier to fully _replace_ the name (this also avoids the issue that names could get very long).

I am also not sure what's the best solution here. I see the issues you bring up with *append*.
The problem with *replace* however is that this does not work when a transform is applied to multiple sources, because they all would end up with the same name.

At least for the issue of how names are concatenated, we could say that MoBIE does not introduce any separators, so that this is up to the user.

**Comment by constantinpape** [comment] 2021-05-16 18:15
Ok, I made the following changes to  the spec:
- "crop" has "shiftToOrigin", which should default to true.
- All source transforms support an optional "name" field. For now, I have written in the description that this name will be appended to the source name.

@tischi let me know if you want to change any of this.

**Comment by tischi** [comment] 2021-05-17 07:44
I am thinking now that the "name" should maybe not be the name of the transform but rather of the transformed source(s). Thus it would be "names", being a list of the same length as the "sources".

I am favoring "replace", because a convenience append mode could be implemented in the software that create the mobie projects (e.g. your python package).

**Comment by constantinpape** [comment] 2021-05-17 07:50
> I am thinking now that the "name" should maybe not be the name of the transform but rather of the transformed source(s). Thus it would be "names", being a list of the same length as the "sources".

Yes, I agree that's much better. I will change it.

**Comment by constantinpape** [comment] 2021-05-17 08:54
Ok, I updated it. To summarize all the relevant changes:
- We support the source transform "crop" now.
- All source transforms ("crop", "affine", "grid") have a new optional field "names", which allows to replace the source names after transformation.

Here's a simplified example of the crop transform: 
```yaml
```
A full project with a crop transform can be found here:
`/g/emcf/pape/mobie-test-projects/mobie_crop`.
I also added the new "names" feature here. And added another bookmark to test the "shiftToOrigin" feature.

**Comment by tischi** [comment] 2021-05-17 14:32
Works ❤️ 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/118506230-6f152480-b72d-11eb-8f1f-3130ba9cd74c.png">

**Comment by martinschorb** [comment] 2021-06-14 10:52
Cool!

I finally found the time to look into that again.
Now, I'd like to combine `crop` with `affine` and eventually `grid` to get the final `view` and I am wondering what  the effect of
```JSON
 "shiftToOrigin": true
```
will be depending on  when the crop happens will be.

**Comment by martinschorb** [comment] 2021-06-14 11:57
An `affine` after a `crop` seems to have no effect at all.
But a `crop` executed last gives good results.

**Comment by martinschorb** [comment] 2021-07-02 13:56
Hi,

I am trying to get a cropped bookmark to work as intended.

This is how it looks at the moment;
```JSON
"crop-bookmark-002": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              -127.0,
              127.0
            ],
            "name": "image-group-0",
            "opacity": 1.0,
            "sources": [
              "_KM140520_Grid3_c154"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "affine": {
            "parameters": [0.6013191061021975,
				-0.3915124093397475,
				-0.696515158463504,
				0.0,
				-0.3915124093397475,
				0.615527182232349,
				-0.683991462860532,
				0.0,
				0.696515158463504,
				0.683991462860532,
				0.2168462883345464,
				0.0],
            "sources": [
              "_KM140520_Grid3_c154"
            ]
          }

        }
      ],
			"crop": {
				"max": [0.54916642, 0.54917618, 0.82490016],
				"min": [-0.55025146, -0.5502417 , -0.27451772],
				"shiftToOrigin": true,
				"sourceNamesAfterTransform": [
					"tomo1-cropped"
				]
			},
			"viewerTransform": {
            "normalizedAffine": [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            "timepoint": 0
        },
      "uiSelectionGroup": "bookmark"
    }
```

This will crop the volume at the physical XYZ limits. However the cropping should happen in the viewer's coordinate frame to ensure all cropped bookmarks are rectangular, so they can be eventually be shown in a grid.
How could I specify the boundaries in "Viewer coordinates"?

**Comment by martinschorb** [comment] 2021-07-05 06:58
So I checked the specs and found out that the `crop` needs to live inside the `sourceTransforms`, otherwise this entry just seems to get ignored. Also it did not contain a `sources` target.

now it looks like:
```JSON
"crop-bookmark-002": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "white",
            "contrastLimits": [
              -127.0,
              127.0
            ],
            "name": "image-group-0",
            "opacity": 1.0,
            "sources": [
              "_KM140520_Grid3_c154"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {  "affine": {
            "parameters": [0.6013191061021975,
							-0.3915124093397475,
							-0.696515158463504,
							0.0,
							-0.3915124093397475,
							0.615527182232349,
							-0.683991462860532,
							0.0,
							0.696515158463504,
							0.683991462860532,
							0.2168462883345464,
							0.0],
            "sources": [
              "_KM140520_Grid3_c154"
            ]
          }
        },
				{
					"crop": {
					"max": [0.54916642, 0.54917618, 0.82490016],
					"min": [-0.55025146, -0.5502417 , -0.27451772],
					"shiftToOrigin": true,
					"sourceNamesAfterTransform": [
						"tomo1-cropped"
					],
					"sources": [
						"_KM140520_Grid3_c154"
					]
				}
			}
      ],
			"viewerTransform": {
            "normalizedAffine": [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            "timepoint": 0
        },
      "uiSelectionGroup": "bookmark"
    }
```

but still does not crop...
If I put the `crop` entry before the `affine, it does crop, but then the cropped volume block is not oriented with the viewer axes.

**Comment by martinschorb** [comment] 2021-07-05 07:33
This now is the `crop-bookmark-002` in the default dataset in `/g/emcf/pape/mobie-test-projects`

**Comment by tischi** [comment] 2021-07-05 09:32
@martinschorb right now the crop is _before_ the affine! I thought you wanted me to test it when you first affine transform and then crop?

**Comment by martinschorb** [comment] 2021-07-05 10:40
> right now the crop is _before_ the affine

yes, I changed that now, but the behaviour is exactly the same. It looks like no matter where in the JSON the crop appears, it is applied first.

BTW: Does your viewer also flicker a lot when scrolling through this dataset?

Martin

**Comment by martinschorb** [comment] 2021-07-05 10:43
I also now specify the source names using `"sourceNamesAfterTransform"` in the affine step and then refer to this source name during the crop. No success...

**Comment by martinschorb** [comment] 2021-07-05 11:03
<img width="690" alt="Screenshot 2021-07-05 at 13 02 15" src="https://user-images.githubusercontent.com/35071867/124461759-4e626600-dd91-11eb-9f7d-9e44599eb125.png">

I often get this stripy appearance with frayed edges.

**Comment by martinschorb** [comment] 2021-07-05 11:05
the black fringes are probably due to zero-value misbehaviour.

https://github.com/bigdataviewer/bigdataviewer-core/issues/126

**Comment by tischi** [comment] 2021-07-05 13:44
@martinschorb 
There were some issue that I fixed (uploaded to MoBIE-beta already).
However, the main issue is that the `viewerTransform` is wrong.
If you press shift+Z you will see that the cropped region is in fact aligned with the xyz axes of the global coordinate system.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/124480307-6b099880-dda7-11eb-8dda-0e0af505835d.png">

If, after you do this, you right click into the BDV window and select "BDV - Log current view" you get: 

```
{"normalizedAffine":[0.19159879848220396,-0.12474791913167561,0.22193119448888496,-0.17207452938728296,-0.12474791913167561,0.19612592939764514,0.21794075911815444,-0.18462491577570794,-0.22193119448888496,-0.21794075911815444,0.06909391016949239,-0.001390719187258005],"timepoint":0}
```

That means the correct `viewerTransform` would be:  `[0.19159879848220396,-0.12474791913167561,0.22193119448888496,-0.17207452938728296,-0.12474791913167561,0.19612592939764514,0.21794075911815444,-0.18462491577570794,-0.22193119448888496,-0.21794075911815444,0.06909391016949239,-0.001390719187258005]`

Could you test what you get if you **don't specify any** `viewerTransform`? 
It may look better.

**Comment by martinschorb** [comment] 2021-07-05 14:30
Hi,

without specifying a viewer transform, it looks tho me that neither the `affine` nor the `crop` are applied at all. I gave some very strange crop limits to test and it still looks as if it is showing the entrie volume (= the first bookmark)

**Comment by tischi** [comment] 2021-07-05 14:38
And in my screenshot above, does that look correct?

**Comment by tischi** [comment] 2021-07-05 14:44
Ok, I agree, it looks as if it is the whole image after the crop.

Could you do me a favor and add another bookmark where you only crop?

**Comment by tischi** [comment] 2021-07-05 15:09
It would also be good to have a crop region that is reasonable, maybe half the size of the original image.
The current one give super weird results for me: `[(0.0, 0.0, 0.0) -- (0.001, 0.001, 300000.0)]`

**Comment by tischi** [comment] 2021-07-05 15:14
I saw that I have write access, so I changed it myself.

**Comment by tischi** [comment] 2021-07-05 15:26
@martinschorb I think it was simply a matter of choosing a crop interval that actually is within the image after you applied the affine transformation:

```
"crop": {
					"max": [0.4, -0.3, 1.6],
					"min": [0.3, -0.4, 1.0],
```

Yields this:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/124493593-1d485c80-ddb6-11eb-88b4-929b0a777004.png">

**Comment by martinschorb** [comment] 2021-07-06 07:23
OK, that makes sense. 
Still the `affine` is not applied here (the volume is shown in its own XYZ cordinates) and that's why my calculated crop boundaries do not work.

Let's take a step al the way back:

- my object of interest is located at voxel position XYZ in the original volume
- the volume gets loaded into BDV with the default transformation specified in the XML bringing it to physical space (just scaling with voxel size).
- I want to orient the volume such that the axis of my object matches a viewer coordinate axis. This is the *affine* transform that is specified in the `sourceTransforms`.
- I then want to crop the volume (in its new orientation) to only show the relevant part
- this subvolume should be shown in a gallery with many others of the same kind.

Is there a conceptual mistake on my side as to where the transforms should be applied? Constantin suggested to force the viewer to the original axes using `viewerTransform`. Or is the underlying problem that there is only one active source and that's why BDV will always adapt to this coordinate system?

**Comment by tischi** [comment] 2021-07-06 07:30
Short zoom?
I'll send a link in a mail.

**Comment by tischi** [comment] 2021-07-20 15:14
@martinschorb 

opening crop-bookmark-imported I am getting this:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2157566/126349330-de2be5ff-04c1-4429-b909-a12c15781341.png">

The width of the crop is about 700 nm.

1. Is this correct? If not or you are not sure, could you please post a screenshot of what you expect?
2. Could you please put two crops there with a grid view on top?

**Comment by martinschorb** [comment] 2021-07-21 09:35
Hi,
this does not really look correct.
I have now created a proper repository for this MoBIE project with all data in

`/g/schwab/Tobias/MoBIE`

I am right now trying to generate one example crop that we can use to check.
Give me 3 minutes...

**Comment by tischi** [comment] 2021-07-21 09:40
Take your time. I will check after lunch ;-)
It would be very helpful if you posted a screenshot here of what it should look like.

**Comment by martinschorb** [comment] 2021-07-21 10:22
the `dataset.json` is there now.

It should look more or less like this:
<img width="350" alt="Screenshot 2021-07-21 at 12 21 29" src="https://user-images.githubusercontent.com/35071867/126473814-7133de81-9a17-4e27-85a6-cb6e4cffa076.png">

**Comment by martinschorb** [comment] 2021-07-21 10:25
@constantinpape  in case you want to reproduce:

```Python
infile = 'Grid3_c550'
xlfile = './Tabellen/CTRL/KM020720_measures_raw1.xlsx'
```

gives me the transformation and crop limits that I manually put into the JSON.

**Comment by tischi** [comment] 2021-07-21 11:25
@martinschorb I have trouble mounting /g/schwab; is it just me?

**Comment by martinschorb** [comment] 2021-07-21 12:06
I can do it and you are member of the group, so it should not be a problem...

**Comment by constantinpape** [comment] 2021-07-21 12:16
I can also access `/g/schwab`

**Comment by tischi** [comment] 2021-07-21 12:17
@martinschorb 

for debugging: could you please also add a bookmark where you _only do the transformation_ without the crop? 

because then we can look there whether the crop bounding box makes sense.

**Comment by martinschorb** [comment] 2021-07-21 12:23
Yep that's in there already.

**Comment by tischi** [comment] 2021-07-21 12:25
Yes, just saw that!

But I think you have a bug because in the crop you are not referring to the correct name of the transformed source:

```
"sourceTransforms": [
        {  "affine": {
            "parameters": [-0.32217264,  0.93204427, -0.16582599,  0.        , -0.93204427,
	       -0.28160441,  0.22801848,  0.        ,  0.16582599,  0.22801848,
	        0.95943177,  0.        ],
						"sourceNamesAfterTransform": [
	  						"tomo1-transformed2"
	  					],
            "sources": [
              "_KM020720_Grid3_c550"
            ]
          }
        },
				{
					"crop": {
					"max": [ 1.36148167, -1.32476456,  1.47788611],
					"min": [ 0.30069031, -2.38555591,  0.41709475],
					"shiftToOrigin": true,
					"sourceNamesAfterTransform": [
						"tomo1-cropped"
					],
					"sources": [
						"tomo1-transformed"
					]
				}
			}
```

**Comment by tischi** [comment] 2021-07-21 12:25
I fixed it for you.

**Comment by tischi** [comment] 2021-07-21 12:28
That's how the crop looks like; similar to yours but wider:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/126488270-27b0b7ae-45b6-4c55-8b1c-88555e8b52dc.png">

**Comment by tischi** [comment] 2021-07-21 12:29
oops, just realizing this looks like the raw data...

**Comment by tischi** [comment] 2021-07-21 12:39
@constantinpape @martinschorb 
There is one issue: the source names in the json and within the xml do not match, e.g.:


xml:
```
      <ViewSetup>
        <id>0</id>
        <name>c515</name>
        <size>2024 2024 769</size>
```

json:
```
_KM270121pos_Grid4_c515
```

Currently, my code expects the source names in the dataset.json to be identical to the source names in the xml. Is that what we also require in the specification?!

**Comment by constantinpape** [comment] 2021-07-21 12:42
> Is that what we also require in the specification?!

Yes, we also require it in the spec. @martinschorb, you will need to fix it in your code that writes the data, this pybdv function is useful here: https://github.com/constantinpape/pybdv/blob/master/pybdv/metadata.py#L843

**Comment by tischi** [comment] 2021-07-21 12:44
Renaming the original sources to other names than what is specified in the xml is something we could implement but I would like to avoid it because we would loose compatibility with the current bdv-playground, see this issue: https://github.com/bigdataviewer/bigdataviewer-playground/issues/186

**Comment by tischi** [comment] 2021-07-21 12:45
@martinschorb is it OK for you if I just manually change the name of the cropped source in the xml such that I can proceed with the testing?

**Comment by tischi** [comment] 2021-07-21 12:46
I just did it 😸 , renamed source in: `bdv-n5/_KM020720_Grid3_c550.xml`

**Comment by tischi** [comment] 2021-07-21 12:51
@martinschorb I think in principle it is working:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/2157566/126491038-e4686afd-a680-4770-8cc4-4c43ae01c497.png">
You (we) still may have to play a bit with the transformation to orient the centriole(?) in the crop bounding box, but at least it seems to be nicely within the crop.

**Comment by martinschorb** [comment] 2021-07-21 13:01
cool.

The goal would be that it is oriented along the `x` axis. At least that is what the linear algebra is supposed to do...

**Comment by martinschorb** [comment] 2021-07-21 13:02
I have to take care of a 5th year Kindergeburtstag now. I'm curious how it proceeds...

**Comment by tischi** [comment] 2021-07-21 13:08
I think I cannot do anything from my side right now. 

Maybe you could just fix above issues and add more of those crops and arrange them in a grid view and then we take it from there.

**Comment by martinschorb** [comment] 2021-07-21 13:41
Is it in a state that you can make it available via the beta update site? Or can you provide me a compiled jar? that would be very helpful so I can play with the transforms.

**Comment by tischi** [comment] 2021-07-21 14:45
I just pushed the latest master to MoBIE-beta (ping @K-Meech @KateMoreva)

**Comment by martinschorb** [comment] 2021-07-22 05:48
Looks good.
I need to work a bit on the transforms (flipping the rotation matrix looks very promising...)

**Comment by martinschorb** [comment] 2021-07-22 06:19
Nailed it!

![Screenshot 2021-07-22 at 08 17 40](https://user-images.githubusercontent.com/35071867/126597060-1c69d150-de87-4887-ad36-b43ec668e7c0.png)

second coordinate axes needs to be treated inverted as always when dealing with MRC format...

I will now try to incorporate the JSON generation into my script and then we are ready.

**Comment by martinschorb** [comment] 2021-07-22 06:26
One general thing we need to consider:

**how do we deal with varying crop sizes?**

- These objects have all varying lengths.
- Since the gallery is displayed in one BDV window, the scale is the same for all of them.
- If I dynamically adjust the crop size according to object size, the gallery tiles will have different sizes.

This probably looks terrible...

I can see a couple of options:
- we use a fixed crop size, with the risk of cutting off some interesting parts of long objects
- we try to find the maximum object length of the dataset and make the tiles that size (risk of having many almost "empty" tiles for small objects)
- we use varying tile sizes and the gallery constructor takes care of ordering them properly so the gallery still looks OK.

How would you go about it?

**Comment by martinschorb** [comment] 2021-07-22 06:33
@constantinpape 

`cropvals` and `vec2mat` (in https://github.com/mobie/MM_centrioles-tomo-datasets/blob/main/centriole_analysis.py) will give you the transformation and crop intervals for any given object specified by the start end end vector in voxel space. Maybe that is useful for other projects as well.

**Comment by tischi** [comment] 2021-07-22 07:11
> we use varying tile sizes and the gallery constructor takes care of ordering them properly so the gallery still looks OK.

I would say lets go for this option. We already discussed at some point (and I cannot find the issue) that some optimal space filling algorithm for 2D tiles of different sizes could be a lot of fun to implement.

**Comment by constantinpape** [comment] 2021-07-22 07:27
> `cropvals` and `vec2mat` (in https://github.com/mobie/MM_centrioles-tomo-datasets/blob/main/centriole_analysis.py) will give you the transformation and crop intervals for any given object specified by the start end end vector in voxel space.

Cool, I will check it out.

> > we use varying tile sizes and the gallery constructor takes care of ordering them properly so the gallery still looks OK.
> 
> I would say lets go for this option. We already discussed at some point (and I cannot find the issue) that some optimal space filling algorithm for 2D tiles of different sizes could be a lot of fun to implement.

Yes, I would also vote for trying this first. I also couldn't find this issue, but it's easy to google: https://en.wikipedia.org/wiki/Rectangle_packing
(and it's important for website rendering, so there should be some good reference implementations)

**Comment by martinschorb** [comment] 2021-07-26 16:17
@tischi it stopped working with my crops (`/g/schwab/Tobias/MoBIE`) You can see the viewer being oriented correctly for a glimpse of a second but it then jumps back to the default view of the source...

Tried with the current beta on Mac and Windows.

**Comment by constantinpape** [comment] 2021-07-26 19:30
@martinschorb maybe this is because you have added `sourceNamesAfterTransformation` now; I think we haven't fully tested this yet.

**Comment by martinschorb** [comment] 2021-07-27 05:57
> sourceNamesAfterTransformation

I head this in earlier versions as well (see `dataset_manual.json` from Friday) and it worked. I don't see what could have changed. There were no updates in Fiji since it worked. The only thing that changed is the `dataset.json` whose entries look the same to me, and the chunk size in the linked n5, but this should be totally irrelevant.

**Comment by martinschorb** [comment] 2021-07-27 06:08
OK, found it. It was the "old" problem that the `sourceNamesAfterTransformation` was missing for the affine trafos.

**Comment by martinschorb** [comment] 2021-07-27 06:25
Looks like it works.

But I cannot close this issue...

**Comment by tischi** [comment] 2021-07-27 06:38
Nice that it works! I will close it.

**Closed by tischi** 2021-07-27 06:38 UTC
